#!/bin/bash

# Welcome to your first Bash Script

hello_message='Hello World!'

current_dir=$(pwd)

list=$(ls -l /workspaces/bash-for-beginners/)

echo "$hello_message from $current_dir files include $list"